#!/usr/bin/env bash
# This script includes the steps to set up a self-signed certificate for
# handling SSL/TLS/HTTPS connections on an nginx server running on Centos7.

mkdir /etc/nginx/ssl

# Generate a 2048 bit RSA private/public key
openssl req \
  -x509 \
  -nodes \
  -days 365 \
  -newkey rsa:2048 \
  -keyout /etc/nginx/ssl/private.key \
  -out /etc/nginx/ssl/public.pem
